### ISSUE TITLE
Widget PUD stops working

### ISSUE THREAD

**Issue by raydurkin** [Rise-Vision/widget-google-calendar#107]
If the number of events on a calendar changes such that it impacts if the widget scrolls or not, PUD stops working.

To reproduce
1. Copy this Presentation https://goo.gl/2Yf9v7
1. Configure the calendar widget to use your calendar.
1. Update the google calendar you use so that just one event will show in the presentation

Because there are not enough events to trigger scrolling, the widget uses the PUD failover. This seems to work as I can see Done/Play events in the log occur every 10 seconds. 

1. Now add 10 events to the google calendar so they show in the widget

When the Widget refreshes it will show all the events (up to what the widget can show), but it will never start scrolling AND the Done event that was taking place every 10 seconds is no longer happening. 

What should happen
If the Widget refreshes and determines it has enough content to scroll, it should scroll and fire Done when finished.

**Comment by stulees** [comment]
Fixed with PR #109
