### ISSUE TITLE
Calendar Widget dissapears when in Schedule with another Presentation that contains PUD Widget.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/widget-google-calendar#110]
**How to recreate**

1. Create Presentation w/Google Calendar Widget
    * Add public calendar to Widget
    * Set Calendar Widget to PUDs
    * Set Calendar Widget Placeholder to be the Presentation's PUD placeholder
2. Create Presentation w/any Widget that supports PUD
   * Set Widget to PUD
   * Set Widget placeholder to PUD placeholder
3. Create a Schedule with above Presentations
   * Set both Presentations to PUD
4. Assign to Display

**What happens**
After a period of time (anywhere between immediately to 60m) the Calendar Widget will no longer appear in the first Presentation created.

**What should happen**
Calendar Widget should always appear during it's Presentation.

**Additional Information**
OS: **Windows 10 x64, Raspbian**
Rise Player: **RisePlayerElectron 2017.05.10.18.06**
Chrome Version: **Chromium 56.0.2924.87**
Viewer Version: **2-01-201705182055**

**Presentations and schedule**
[Presentation 1](https://apps.risevision.com/editor/workspace/fe592bc7-21cd-4629-a52a-0a33c378dc29/?cid=e113f8d6-de1c-4c26-b160-4ef1c4589957)
[Presentation 2](https://apps.risevision.com/editor/workspace/7bf2f6b3-4d07-4b1f-80f1-8713ad4a62f2/?cid=e113f8d6-de1c-4c26-b160-4ef1c4589957)
[Schedule](https://apps.risevision.com/schedules/details/5adc8234-2806-444e-8a0f-d939fbb22832?cid=e113f8d6-de1c-4c26-b160-4ef1c4589957)

**Comment by btfrise** [comment]
@alanclayton FYI, this is a confirmation of a defect reported in ticket 12704, and https://community.risevision.com/rise_vision_inc/topics/google-calendar-scrolling-daily-variable-lengths

**Comment by btfrise** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(2) Calendar Defect: Issue 110. Calendar disappears when in Schedule using PUD.](https://trello.com/c/pPBelsEu/4361-2-calendar-defect-issue-110-calendar-disappears-when-in-schedule-using-pud)

**Comment by stulees** [comment]
@btfrise During the period of time between immediately and 60mins did you modify the events in your Google Calendar?

**Comment by btfrise** [comment]
@stulees No, I just leave it running.

**Comment by stulees** [comment]
@btfrise Fixed with PR #111
