### ISSUE TITLE
Scrolling will freeze after about 30 minutes

### ISSUE THREAD

**Issue by raydurkin** [Rise-Vision/widget-google-calendar#112]
User has google calendar widget in presentation.

Set to show a week, scroll continuously, fast

Nothing I can find in settings that is unusual.

After presentation plays on display for about 30 minutes it stops scrolling.  It will start again if you publish the presentation or reboot.    This issue does not happen in preview.

client has issue on raspberry pi but I run the presentation on a linux box at plexpod and have the same issue.

link to client presentation:  https://apps.risevision.com/editor/workspace/13daafec-2cbc-4028-bf8a-e7ec77370a72/?cid=a2135270-c90c-44f9-aeac-bf0359c16219

link to presentation in rise account - https://apps.risevision.com/editor/workspace/f49b37f7-b508-401b-8b2b-a550dd4fc954/?cid=fee1f642-cdd1-4bc4-8f93-1fc97cb00d55

Presentation is running on 40" cart in plexpod now
Screenconnect link: https://connect.risevision.com/Host#Access/*KC_Uptime//b7032783-3d80-4ea2-a1ed-78270b459a9b

**Comment by raydurkin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(1) Issue 112: Google Calendar widget stops scrolling after about 30 minutes](https://trello.com/c/ABCRFzfk/5424-1-issue-112-google-calendar-widget-stops-scrolling-after-about-30-minutes)

**Comment by rodrigopavezi** [comment]
Fix https://github.com/Rise-Vision/widget-google-calendar/pull/113 has been released. cheers
