### ISSUE TITLE
Fonts broken

### ISSUE THREAD

**Issue by pingabl3** [Rise-Vision/widget-google-calendar#117]
Are fonts broken on this widget? It seemed to be working fine, but now any changes I make to the font settings are not reflected in the presentation, it just shows the small default font.

**Comment by sheadarlison** [comment]
@pingabl3 Thanks for reporting this, we're looking into it right now and I'll update this issue when it's fixed.

**Comment by sheadarlison** [comment]
Hi @pingabl3 this is fixed now, you may need to clear your cache to pick up the update. 

Thanks!
