### ISSUE TITLE
When using a non-default Google Font, the Calendar does not show in a Presentation

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/widget-google-calendar#120]
<b>How it works now</b>
1. Add a Public Calendar to your Presentation using the Calendar Widget.
2. Select to use a Google Font from the "More Fonts" option for the content that you want to show from that Calendar.
3. Preview or play your Presentation on a Display. Notice that the Calendar does not show up.

<b>How it should work:</b>
Regardless if you are using a non-default .Google Font or not, the calendar should show the text.

**Comment by robb-price** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue 120: Calendars with Custom Fonts do not show.](https://trello.com/c/lB6J4E9Y/7732-issue-120-calendars-with-custom-fonts-do-not-show)

**Comment by rudibravo** [comment]
@robb-price fix is deployed. please verify.

**Comment by robb-price** [comment]
@rudibravo Confirmed and verified. Thanks.
