### ISSUE TITLE
Calendar not refreshing

### ISSUE THREAD

**Issue by cyeelesd** [Rise-Vision/widget-google-calendar#122]
I added a new event to the public calendar feeding the widget. In the past, the new event showed up in the presentation within 5 to 10 minutes, but after 30 minutes the event does not appear, and requires a restart of the Rise Vision player or - less aggressively - making an innocuous change to the presentation and then re-publishing it. 

I noticed this loss of functionality after encountering [Issue #120](https://github.com/Rise-Vision/widget-google-calendar/issues/120). I don't know if it's related or coincidental with the deployed fix.

**Comment by sheadarlison** [comment]
Hi @cyeelesd, 

We increased the refresh time on the widget to 1 hour to resolve issue #114. Our refresh had been set to 5 minutes and it was causing us to go over our Google Calendar API quota. 

I'll discuss with my team tomorrow to see if we have options for decreasing the refresh time and will update you here. 

Thanks,
Shea

**Comment by cyeelesd** [comment]
Thanks for the response. FWIW, we were running into the "calendar not public" problem early on and when we set the display to reboot at an off hour (under the settings for Display), this seemed to remedy the problem.

**Comment by sheadarlison** [comment]
Hi @cyeelesd, 

We're going to decrease the refresh to 30 minutes, once the change is made I'll update and close this issue. 

Let me know if you have any questions. 

Thanks

**Comment by sheadarlison** [comment]
Hi @cyeelesd we've made the update. 

Thanks

FYI @robb-price closing this issue.
