### ISSUE TITLE
Calendar does not scroll correctly on Windows Players

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/widget-google-calendar#133]
### What is the expected behavior?
Google Calendar Widget should scroll as expected on all Players.

### What is the actual behavior?
The Google Calendar Widget scrolls as expected on Linux and ChromeOS, but does not scroll after the first time on the Windows Player.

### What steps can be taken to replicate the problem?
1. Use this Presentation: https://apps.risevision.com/editor/workspace/2932c9d3-6a31-40bc-b200-d4185a4e8b87/?cid=556323b8-984c-4127-aa08-4d73d019bcb8, and assign it to a ChromeOS, Linux, and Windows Player.

2. Notice that it will continue scrolling after reaching the end on only ChromeOS and Linux. It will always remain at the end on the Windows Player.

For further clarification: https://goo.gl/jnW3a9

**Comment by santiagonoguez** [comment]
Solved in latest stable branch, will still be monitored the next 24 hours.
