### ISSUE TITLE
Events that run past midnight do not show start and end times.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/widget-google-calendar#135]
**How to recreate**

1. Create a new Google Calendar and set up sharing.
2. Add two events to that new calendar.
 - One that begins and ends today before midnight (E.g. 6:30pm-7:30pm)
 - One that starts before midnight and ends after midnight (E.g. 11:00pm-12:30am)
3. Create a Presentation with a Google Calendar Widget
4. Add the calendar created above to the Widget
5. Preview the Presentations

**What happens**
The event from 6:30pm-7:30pm shows start and end times. The event from 11:00pm-12:30am does not show start and end times.

**What should happen**
Both events should show start and end times.

[Image of preview](https://www.screencast.com/t/lUNLupPn7d)
[Image of Google Calendar events](https://www.screencast.com/t/t8YtUVFpcx76)

**Comment by stulees** [comment]
This has been fixed with #136, FYI @btfrise
