### ISSUE TITLE
Event Description Formatting

### ISSUE THREAD

**Issue by sheadarlison** [Rise-Vision/widget-google-calendar#140]
A customer used bullet points in the description of Google Calendar events as a workaround to create line breaks when the content was rendered on the Display. The bullet points, font size, colors, etc... were not rendered, but when text was broken up using bullet points it created line breaks which made the calendar event easier to read on a display. Recently something changed and the bullet points are no longer creating line breaks. 

If you need more context please look at ticket 41047 in Zendesk or msg me.

**Comment by stulees** [comment]
@sheadarlison The customer no longer needs to use bullet points in the description of events as a workaround. This was addressed in issue #137 and fixed with #139 .

**Comment by sheadarlison** [comment]
@stulees did #139 cause the problem described above?

**Comment by stulees** [comment]
@sheadarlison The calendar API encodes event description, so #139  decodes the value and ensures to render as HTML, that way any HTML tags in the description are actually applied as HTML. 

The problem described sounds like a user was previously accounting for their HTML not being rendered. They don't need to apply a workaround anymore, they can apply HTML in their event description.

**Comment by sheadarlison** [comment]
@stulees unfortunately this customer doesn't want to use HTML in their event description. See the comments here: https://risevision.zendesk.com/agent/tickets/41047

Is there any way to please both customers?

**Comment by stulees** [comment]
@sheadarlison The only way to please both may have to involve a new widget setting. We'll need to look into it and see what options we have. Can you please include a link to the users presentation and schedule in this issue or on the Trello card? Thanks

**Comment by sheadarlison** [comment]
@stulees the Presentation is linked on the card. Thanks

**Comment by stulees** [comment]
This has been fixed with #141
