### ISSUE TITLE
Despite the Calendar being public, the Widget shows it as Not Public

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/widget-google-calendar#149]
### What is the expected behavior?
If the Calendar is set as Public, it should show in the Presentation.

### What is the actual behavior?
Despite the Calendar being public, a message shows in the Presentation stating that the Calendar is not public.

### What steps can be taken to replicate the problem?
Add the Calendar Template, or the Calendar Widget to any Presentation, and use a Public Calendar ID. Notice that it shows the message that the calendar is not public.

**Comment by tejohnso** [comment]
Closed. See [Post mortem](https://docs.google.com/document/d/1iz9fnAA527wjphnU9N_BrOaRMhRykVpGOmhxC_hmLSk/edit#)
