### ISSUE TITLE
User is not told if configured Calendar can't be accessed

### ISSUE THREAD

**Issue by alanclayton** [Rise-Vision/widget-google-calendar#162]
**Current User Experience**
There is no error shown to the user when they configure the widget to use a Google Calendar that is not publicly accessible. As a result, the user is confused and not sure what to do next so that their events will show.  The following screenshot is what a user will see when the widget is configured to use a calendar that is not publicly accessible. 

![image](https://user-images.githubusercontent.com/6854911/124660793-4deacd80-de6c-11eb-9a7c-51b3cbaccdb4.png)

**Expected User Experience**
After providing a Google Calendar ID, and every time I open the widget settings thereafter, I should be told if the provided Calendar ID is not publicly accessible and I should not be able to save the widget settings until I have resolved the error. 

![image](https://user-images.githubusercontent.com/6854911/124665375-43cbcd80-de72-11eb-8c44-133f9e38ffdb.png)

The error message should link to the [How do I make my google calendar public](https://help.risevision.com/hc/en-us/articles/115002181123-How-do-I-make-my-google-calendar-public-and-get-the-calendar-ID-)

**Reproduction Steps**
1. Add Calendar Widget to a Presentation
2. Configure the widget to use a Calendar ID for a non pubic calendar.

**Comment by stulees** [comment]
@alanclayton I've done a code review of the widget settings and done a brief assessment of what's involved to resolve this defect. I'm estimating this to be no less than a 5pt investment (3+ days). Given this is a Widget and we do plan to build a Calendar component in the future, I'm wondering if this is worth the investment and perhaps should instead be moved to a backlog component pitch (after enabling Component standard). Thoughts?

**Comment by alanclayton** [comment]
@stulees creating a new calendar component doesn't eliminate the thousands of displays using the widget. Can you clarify?

**Comment by stulees** [comment]
@alanclayton This defect only pertains to the Widget settings. If and when we build a Calendar component, we're going to have to build a separate settings codebase for that also in Template Editor. My main question here is regarding whether resolving this defect is worth the investment now, considering we will also develop a Calendar component in the future.

**Comment by stulees** [comment]
@alanclayton If so, then we will proceed with what I estimated above. Thanks

**Comment by alanclayton** [comment]
@stulees Unless there is risk of re-work, or more efficient to wait for calendar component, I think we should just get it done. Can you confirm? Thanks

**Comment by stulees** [comment]
@alanclayton There is no risk of re-work for the Widget. When you say "more efficient to wait for Calendar component", can you clarify?

**Comment by alanclayton** [comment]
@stulees by more efficient, will it take less time to do if you wait until calendar component.

**Comment by stulees** [comment]
@alanclayton It sounds like this functionality is wanted in the settings for both the Widget and a future Component. It won't take less time to implement in the Widget if we wait until doing the Component first as they are separate code bases. We'll proceed with implementing in the Widget now for the estimated effort I mentioned above. Thanks

**Comment by stulees** [comment]
@alanclayton This has now been fixed with PR #166 , closing the issue, thanks
