### ISSUE TITLE
Manual Input for Font Sizes

### ISSUE THREAD

**Issue by kraymitchell** [Rise-Vision/widget-google-calendar#60]
I noticed today that you are unable to set manual font sizes for items in the Calendar.

I want 22pt but my only options are 18, 20 and 24.

While I'm sure I can change this in the custom widget I did, for those using the default Widget, I'm sure they would like this ability back as you could easily change to a manual number with a gadget.

**Comment by donnapep** [comment]
This isn't an enhancement to be made to the Calendar Widget per se, but rather to the [BootstrapFormHelpers](https://github.com/Rise-Vision/BootstrapFormHelpers), which all Widgets use. This will likely be addressed with the next round of changes to the Text Widget.
