### ISSUE TITLE
Localized strings don't appear in settings dialog in widget previewer

### ISSUE THREAD

**Issue by OllieJones** [Rise-Vision/widget-google-calendar#75]
The localized strings don't appear in the settings dialog when I attempt to use this with the widget previewer.

I know you've changed the i81n / l12n procedure lately, but there some to be some installation prerquisites that aren't set up right.

To get this problem I did this stuff.

    git clone https://github.com/Rise-Vision/widget-google-calendar.git
    cd widget-google-calendar
    npm install
    bower install
    gulp build

then run the widget with the Windows previewer.

I get this.

![image](https://cloud.githubusercontent.com/assets/9804013/5692826/33c1d1e6-98d3-11e4-9767-b7f2b7a49123.png)

**Comment by OllieJones** [comment]
By the way, the localized strings display OK in the e2e test.

Also, I've tried this with the latest version of the widget previewer, and with a couple of previous versions.

**Comment by OllieJones** [comment]
By the way, changing `src/config/dev.js` so it contains this stanza instead of the one that's there fixes this problem. It seems to be a config problem related to the widget previewer (the dev environment).

	if (typeof angular !== "undefined") {
	  angular.module("risevision.common.i18n.config", [])
		.constant("LOCALES_PREFIX", "locales/translation_")
		.constant("LOCALES_SUFIX", ".json");
	}

**Comment by donnapep** [comment]
@OllieJones You need to run the `settings.html` file that is in the `src` folder when using the widget previewer app, not the `dist` folder. I think this makes more sense anyway since this means you won't have to rebuild every time you make a change. Thx.
