### ISSUE TITLE
`gulp test` grumbles about missing sinon-chai plugin

### ISSUE THREAD

**Issue by OllieJones** [Rise-Vision/widget-google-calendar#77]
Running `gulp test` causes this message to be generated:

    [14:25:12] Starting 'test:unit:widget'...
    [14:25:12] Starting Karma server...
    WARN [plugin]: Cannot find plugin "sinon-chai".
      Did you forget to install it ?
      npm install sinon-chai --save-dev
    INFO [karma]: Karma v0.12.31 server started at http://localhost:9876/

Doing what it says  -- running `npm install sinon-chai --save-dev` resolves the problem, and the tests go ok.

Actually, the tests go ok in any case.

**Comment by donnapep** [comment]
Fixed by PR #79.
