### ISSUE TITLE
What is the correct procedure for translating and localizing now?

### ISSUE THREAD

**Issue by OllieJones** [Rise-Vision/widget-google-calendar#78]
It seems the procedure for preparing text for the settings screen, and localizing it, has changed.

Can you offer a pointer to the new procedure?

**Comment by donnapep** [comment]
@OllieJones All of the translations are coming from [common-i18n](https://github.com/Rise-Vision/common-i18n) now. This repo is brought into our Widgets by virtue of the fact that they bower install widget-settings-ui-components, so there's no need to bower install it again from the Widget. The translations can be found in the `src/locales` folder of `common-i18n`. Each Widget has its own JSON file, but there are also some common translations that all Widgets are free to use in `labels.json`.

We're still figuring translations out and will be updating the ReadMes accordingly.

Thx.
