### ISSUE TITLE
Google Calendar Widget Settings page fails to load properly

### ISSUE THREAD

**Issue by justinsmith1** [Rise-Vision/widget-google-calendar#86]
When clicking on the configure button for the Google Calendar Widget, not all headings are loading properly on the widget settings page.

Here you can see the title, location, description headings are missing: http://screencast.com/t/M1SitM9d6

This is an intermittent issue. When I was smoke testing around 11AM CST, I did not see this happening. But now, as of 3:45PM CST it's happening. I can click 'reload frame' in my browser, and this will resolve the issue.

Expected behavior: all headings should show up on the Widget settings page as in this screenshot: http://screencast.com/t/reI6KAsHjG

**Comment by alanclayton** [comment]
@donnapep can you look into this tomorrow? 

@justinsmith1 can you also confirm OS/browser version and provide a link to the presentation where you are seeing this?

**Comment by donnapep** [comment]
@justinsmith1 My guess would be this is a caching issue. If you still see it after emptying your cache, let me know. Thx.
