### ISSUE TITLE
Extra space below event time and title (in beta version) that doesn't match production.

### ISSUE THREAD

**Issue by mfisher11** [Rise-Vision/widget-google-calendar#88]
In the current beta version (with residual production settings), the calendar appears fine.
However, if you enter placeholder properties, then widget settings, *make no changes*, then save twice:
(this can also be be seen by choosing a custom layout, then changing it back afterwards)

Expected behavior:   no change between production and beta.
Actual behavior:  extra space below items that can break current layout expectations.

Screenshot (production vs. beta)
http://screencast.com/t/j8gGruYXgc

Manage presentation:
http://rva.risevision.com/#PRESENTATION_MANAGE/id=3cd75386-e723-46f5-9806-0da8c880ad7c/company=e514fd51-fadd-4e19-94af-f92549772c7f

Preview presentation:
http://preview.risevision.com/Viewer.html?type=presentation&id=3cd75386-e723-46f5-9806-0da8c880ad7c

**Comment by donnapep** [comment]
@mfisher11 This is fixed. Thx.

**Comment by alanclayton** [comment]
@donnapep Thanks! @mfisher11 can you verify?

**Comment by mfisher11** [comment]
@alanclayton @donnapep   Confirmed.
