### ISSUE TITLE
Cannot press 'Configure'

### ISSUE THREAD

**Issue by hcs0** [Rise-Vision/widget-google-calendar#99]
A user has created a Google Calendar widget and hosted on their server.  When they add it on the presentation they are unable to press 'Configure' on RVA.

**What I have done to troubleshoot**

1. Copied the user presentation code and confirmed that I cannot press Configure.

2. Edited the HTML with the user Google Calendar ID and was able to save/preview their Calendar.

3. Added a new Placeholder (via the usual add Placeholder process) and added the user Google Calendar ID and was able to save/preview their Calendar.

**What I expected**

This is the first time I have come across a user that have branched off the repo for the Google Calendar widget and host on their own server so I am not too familiar with the process, but I expected the user to be able to implement the widget from GitHub and then host the calendar on their server.

**Workaround**

1. Add the Google Calendar widget from the Store.

2. Add the Calendar ID.

3. Configure the Style in the Placeholder

4. Go to the HTML view and replace the default link to where the calendar is hosted on the user's server

5. When the widget is being configured in the Placeholder, the code will default back to the Amazon AWS link so the user needs to go to HTML view and then replace the link with their own web server link.  The style will still remain.

**Other factors***
There may be other factors ie not configuring the widget when first uploaded.  When I initially inspected the code there were some parameters missing.

**Comment by alanclayton** [comment]
@hcs0 Do we really need to look into this given we don't have control over the server the widget is hosted on?

**Comment by hcs0** [comment]
@alanclayton No we don't need to look over this since yes it's dependent on user's server. Closing
